---
title: "Replicate and extend analyses from Antao et al. 2020"
output: 
    github_document: default
---

# Load data
```{r setup, echo=FALSE}
library(glmmTMB)
library(data.table)
library(here)

# Antao data
load(url('https://github.com/lauraantao/Temp_Biodiv_Change/raw/master/R/lm_slopes_meta_temperature3.Rdata')) # load Antao data
dat <- data.table(lm_slopes_meta_temperature3)

datRichMar <- droplevels(dat[model_id == 'logS_lm' & REALM=='Marine',])
datRichTerr <- droplevels(dat[model_id == 'logS_lm' & REALM=='Terrestrial',])

# my data
trends <- fread(here('output', 'slope_w_covariates.csv.gz'))

```

# Fit richness model
The richness (logS) model matches the published results if the error and RE terms are realm-specific.
```{r}
# published model
mod0 <- glmmTMB(slope ~ 0 + new_sTempYear:REALM + TempGAMCoef:REALM + TempGAMCoef:new_sTempYear:REALM
                +(0 + TempGAMCoef|REALM/taxa_mod1) +(1|REALM/taxa_mod1/STUDY_ID), 
                disp = ~std.error*REALM,
                data = dat[model_id == 'logS_lm',])

summary(mod0)
```

Adding an intercept to allow turnover at 0 temperature change doesn't alter the results
```{r}
# add an intercept to allow some turnover at 0 temperature change and ave temp. wouldn't converge with realm-specific intercept.
mod1 <- glmmTMB(slope ~ 1 + new_sTempYear:REALM + TempGAMCoef:REALM + TempGAMCoef:new_sTempYear:REALM
                +(0 + TempGAMCoef|REALM/taxa_mod1) +(1|REALM/taxa_mod1/STUDY_ID), 
                disp = ~std.error*REALM,
                data = dat[model_id == 'logS_lm',])
summary(mod1)
```

Another approach to adding an intercept: realm-specific, but with simpler REs. REALM-specific RE intercepts won't converge.
```{r}
# realm-specific intercept. Simplify REs that were near zero.
mod2 <- glmmTMB(slope ~ 0 + REALM + new_sTempYear:REALM + TempGAMCoef:REALM + TempGAMCoef:new_sTempYear:REALM
                +(0 + TempGAMCoef|REALM/taxa_mod1) +(1|taxa_mod1/STUDY_ID), 
                disp = ~std.error*REALM,
                data = dat[model_id == 'logS_lm',])


summary(mod2)
```

# Compare datasets
```{r}
# merge
comb <- merge(dat, trends[duration_group == 'Ally1', ], by = c('STUDY_ID', 'rarefyID', 'REALM', 'rarefyID_y'))

# compare
comb[, plot(startYear, year1)]
comb[, plot(endYear, year2)]
comb[, plot(TempGAMCoef, temptrend)]; abline(0,1)
comb[, plot(new_sTempYear, tempave.sc, col = c('green', 'blue')[(REALM=='Marine')+1])]; abline(0,1)
comb[model_id == 'logS_lm' & measure == 'Jtu', plot(slope, disstrend, xlab = 'logS slope', ylab = 'Jtu slope')]
comb[model_id == 'Gains_lm' & measure == 'Jtu', plot(slope, disstrend, xlab = 'Gains slope', ylab = 'Jtu slope')]
comb[model_id == 'Losses_lm' & measure == 'Jtu', plot(slope, disstrend, xlab = 'Losses slope', ylab = 'Jtu slope')]

comb[model_id == 'logS_lm' & measure == 'Jbeta', plot(slope, disstrend, xlab = 'logS slope', ylab = 'Jbeta slope')]
comb[model_id == 'Gains_lm' & measure == 'Jbeta', plot(slope, disstrend, xlab = 'Gains slope', ylab = 'Jbeta slope')]
comb[model_id == 'Losses_lm' & measure == 'Jbeta', plot(slope, disstrend, xlab = 'Losses slope', ylab = 'Jbeta slope')]

comb[model_id == 'logS_lm' & measure == 'Horn', plot(slope, disstrend, xlab = 'logS slope', ylab = 'Horn slope')]
comb[model_id == 'logN_lm' & measure == 'Horn', plot(slope, disstrend, xlab = 'logN slope', ylab = 'Horn slope')]
comb[model_id == 'Gains_lm' & measure == 'Horn', plot(slope, disstrend, xlab = 'Gains slope', ylab = 'Horn slope')]
comb[model_id == 'Losses_lm' & measure == 'Horn', plot(slope, disstrend, xlab = 'Losses slope', ylab = 'Horn slope')]

```


