---
title: "Turnover vs. temperature data prep"
output: 
    html_notebook: default
    #html_document: default
    #github_document: default # latter for displaying on github
---

```{r setup}
library(data.table)
library(ggplot2)
library(lme4)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # tell RStudio to use project root directory as the root for this notebook. Needed since we are storing code in a separate directory.
```

### Load data
```{r load data}
# BioTime
load('data/biotime_blowes/bt_malin.Rdata')
bt <- data.table(bt_malin); rm(bt_malin)

# Temperature trends from CRU TS (on land)
tmptrendbyyr <- fread('output/cruts_tmptrend_byyear.csv.gz', drop = 1)
tmptrendallyr <- fread('output/cruts_tmptrend_allyear.csv.gz', drop = 1)

# Temperature trends from ERSST (ocean)
ssttrendbyyr <- fread('output/ersst_ssttrend_byyear.csv.gz', drop = 1)
ssttrendallyr <- fread('output/ersst_ssttrend_allyear.csv.gz', drop = 1)

# Seasonality
seascru <- fread('output/cruts_seas.csv.gz', drop = 1)
seasersst <- fread('output/ersst_seas.csv.gz', drop = 1)

# Average temperature
tavecru <- fread('output/cruts_tmpave_allyear.csv.gz', drop = 1)
taveersst <- fread('output/ersst_sstave_allyear.csv.gz', drop = 1)

# NPP
npp <- fread('output/npplandocean.csv.gz')

# Body size
bs <- fread('output/mass_byrarefyid.csv.gz', drop = 1)
bs[, ':='(STUDY_ID = NULL, REALM = NULL, taxa_mod = NULL)] # remove unnecessary columns 
```

### Assemble dataset of trends (turnover and temperature) and covariates
```{r assemble trends and covariates}
# calculate temporal turnover
calctrend <- function(y, YEAR, nm = 'y'){ # function to calc trends
    mod <- lm(y ~ YEAR)
    out <- list(y = coef(mod)[2], # coef for the slope
         y_se = sqrt(diag(vcov(mod)))[2]) # SE
    names(out) <- c(nm, paste0(nm, '_se'))
    return(out)
}

setkey(bt, STUDY_ID, rarefyID, YEAR)
trends <- bt[, calctrend(Jtu_base, YEAR, 'Jtutrend'), 
    by = .(REALM, Biome, taxa_mod, STUDY_ID, rarefyID, rarefyID_x, rarefyID_y)] # calculate trend in Jaccard turnover from first year, plus SEs
trends2 <- bt[, calctrend(Jbeta_base, YEAR, 'Jbetatrend'), 
    by = .(rarefyID)] # calculate trend in total Jaccard' beta diversity's from first year, 
trends3 <- bt[, calctrend(1-Horn_base, YEAR, 'Horntrend'), 
    by = .(rarefyID)] # calculate trend in Horn-Morisita from first year. Convert to dissimilarity.
trends4 <- bt[, .(Strend = coef(lm(I(log(S)) ~ YEAR))[2]), by = .(rarefyID)] # trend in log(S)
nyrBT <-  bt[, .(nyrBT = length(YEAR)), by = .(rarefyID)] # number of years in time-series

trends <- merge(trends, trends2) # merge in total J and Horn-Morisita
trends <- merge(trends, trends3)
trends <- merge(trends, trends4)
trends <- merge(trends, nyrBT)
rm(trends2, trends3, trends4, nyrBT)
```

Find a minimum trend SE to use in cases where missing
```{r find minse}
trends[Jtutrend_se>0, hist(log10(Jtutrend_se))] # plot of SE on the trends
trends[Jtutrend_se>0, plot(nyrBT, Jtutrend_se, log = 'y')]

fillse <- trends[Jtutrend_se > 1e-10, mean(Jtutrend_se)] # find smallest non-zero se, avoiding the perfect fits
trends[, Jtutrend_se_nz := Jtutrend_se] # create an SE that is not zero or NA
trends[is.na(Jtutrend_se_nz), Jtutrend_se_nz := fillse] 
trends[Jtutrend_se_nz < 1e-10, Jtutrend_se_nz := fillse] 

trends[, hist(log10(1/(Jtutrend_se_nz^2)))] # inverse variance, used for weighting
trends[, plot(nyrBT, 1/(Jtutrend_se_nz^2), log = 'y')]

```

```{r add covariate data}
# add temperature trends
trends <- merge(trends, tmptrendbyyr, all.x = TRUE, by = 'rarefyID') # add temperature trend (years that match biotime)
trends <- merge(trends, tmptrendallyr[, .(rarefyID, tmptrendallyr)], all.x = TRUE, by = 'rarefyID') # add temperature trend (all years from first to last of each time-series)
trends <- merge(trends, ssttrendbyyr[, .(rarefyID, ssttrendbyyr)], all.x = TRUE, by = 'rarefyID') # sst
trends <- merge(trends, ssttrendallyr[, .(rarefyID, ssttrendallyr)], all.x = TRUE, by = 'rarefyID')

# add covariates
trends <- merge(trends, seascru[, .(rarefyID, seas_cruts)], all.x = TRUE, by = 'rarefyID') # seasonality from CRU TS
trends <- merge(trends, seasersst[, .(rarefyID, seas_ersst)], all.x = TRUE, by = 'rarefyID') # seasonality from ERSST
trends <- merge(trends, tavecru[, .(rarefyID, tmpaveallyr)], all.x = TRUE, by = 'rarefyID')
trends <- merge(trends, taveersst[, .(rarefyID, sstaveallyr)], all.x = TRUE, by = 'rarefyID')
trends <- merge(trends, npp, all.x = TRUE, by = 'rarefyID') # npp, centered and scale
trends <- merge(trends, bs, all.x = TRUE) # npp, centered and scale
```

Do some basic checks
```{r basic checks}
# basic checks
trends
trends[, .(minJtu = min(Jtutrend), maxJtu = max(Jtutrend), minJbe = min(Jbetatrend), maxJbe = max(Jbetatrend), 
           minHo = min(Horntrend, na.rm = TRUE), maxHo = max(Horntrend, na.rm = TRUE), minS = min(Strend), maxS = max(Strend)), by = REALM]
trends[, .(nJtu = sum(Jtutrend < 0), nS = sum(Strend < 0)), by = REALM] # why are some turnover trends < 0?
trends[, .(nJ = sum(Jtutrend > 0), nS = sum(Strend > 0)), by = REALM]
```

```{r basic graphs of turnover metrics}
# are turnover calculations correlated?
ggplot(trends, aes(Jbetatrend, Jtutrend)) +
    geom_point() +
    geom_smooth()

ggplot(trends, aes(Jbetatrend, Horntrend)) +
    geom_point() +
    geom_smooth()

```

```{r basic graphs of temperatures}
# are the temperature trends correlated?
# compare trends calculated from all sampled years in BioTime vs. all years from min to max year in BioTime
ggplot(trends, aes(tmptrendallyr, tmptrendbyyr)) +
    geom_point() +
    geom_smooth()

ggplot(trends, aes(ssttrendallyr, ssttrendbyyr)) +
    geom_point() +
    geom_smooth()

# compare temperature trends from CRU TS vs ERSST
ggplot(trends, aes(tmptrendallyr, ssttrendbyyr)) + # ERSST more muted at fastest rates of change in CRU TS
    geom_point() +
    geom_smooth()

# average temperature from CRU TS and ERSST
ggplot(trends, aes(tmpaveallyr, sstaveallyr, color = rarefyID_y)) + # ERSST more muted at fastest rates of change in CRU TS
    geom_point() +
    geom_smooth()

# compare seasonality from CRU TS and ERSST
ggplot(trends, aes(seas_cruts, seas_ersst, color = rarefyID_y)) + # ERSST more muted at fastest rates of change in CRU TS
    geom_point() +
    geom_smooth()
```

### Combine CRU TS and ERSST
```{r combine cruts and ersst}
# temperature trend
trends[ , temptrend_comb_allyr := tmptrendallyr] # CRU TS for land and freshwater
trends[REALM == 'Marine', temptrend_comb_allyr := ssttrendallyr] # ERSST for marine

# average temperature
trends[, tempave_comb := tmpaveallyr]
trends[REALM == 'Marine', tempave_comb := sstaveallyr]

# seasonality
trends[, seas_comb := seas_cruts]
trends[REALM == 'Marine', seas_comb := seas_ersst]
```

### Center and scale covariates
``` {r center and scale}
trends[, temptrend_comb_allyr.sc := scale(temptrend_comb_allyr)]
trends[, temptrend_comb_allyr_abs.sc := scale(abs(temptrend_comb_allyr))]
trends[, seas_comb.sc := scale(seas_comb)]
trends[, tempave_comb.sc := scale(tempave_comb)]
trends[, npp.sc := scale(npp)]
trends[, mass_geomean.sc := scale(mass_geomean)]
```


### Write out
```{r write out}
write.csv(trends, gzfile('output/turnover_w_covariates.csv.gz'))
```

