---
title: "Gains/losses and turnover rate"
output: 
    github_document: default
---
Do the proportion of gains and losses differ by realm, temperature state, or microclimate heterogeneity?

```{r setup, include=FALSE}
library(data.table) # for handling large datasets
library(ggplot2) # for some plotting
library(glmmTMB) # for beta regression
library(here) # for navigating directories in the repo
if(Sys.info()['nodename'] == 'annotate.sebs.rutgers.edu'){
  library('mgcv', lib.loc = '/usr/lib64/R/library') # when running on Annotate. Need to load 1.8-26, not 1.8-33, for geom_smooth() in ggplot
} else {
  library('mgcv')
}
source(here('code', 'util.R')) # simple utility functions

# tell RStudio to use project root directory as the root for this notebook. Needed since we are storing code in a separate directory.
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) 

```

# Load data and set up
```{r}
# gains and losses data
load('data/biotime_blowes/bt-rarefy-collate.Rdata') # loads rarefied_alpha_medians and rarefied_beta_medians
rarefied_alpha_medians <- as.data.table(rarefied_alpha_medians)
rarefied_beta_medians <- as.data.table(rarefied_beta_medians)

# biotime community dissimilarity data
bt <- fread('output/turnover_w_covariates.csv.gz') # the timeseries that pass QA/QC. from assemble_turnover_covariates.Rmd
nrow(bt)

# add initial dissimilarities
bt[, minduration := min(duration), by = rarefyID]
initdiss <- bt[duration == minduration, .(Jtu.init = mean(Jtu.sc)), by = .(rarefyID)] # initial dissimilarities
bt <- merge(bt, initdiss[, .(rarefyID, Jtu.init)])
nrow(bt)

# add gains and losses
bt <- merge(bt, rarefied_alpha_medians[, .(rarefyID, year1 = YEAR, S1 = S)], by = c('rarefyID', 'year1')) # merge in num species in first year
bt <- merge(bt, rarefied_alpha_medians[, .(rarefyID, year2 = YEAR, S2 = S)], by = c('rarefyID', 'year2')) # and second year
bt <- merge(bt, rarefied_beta_medians[, .(rarefyID, year1 = as.numeric(YEAR1), year2 = as.numeric(YEAR2), gains, losses)], by = c('rarefyID', 'year1', 'year2')) # merge in num gains and losses. not clear why YEAR1 and YEAR2 got read as characters, but coercing to numeric seems fine.
nrow(bt)

# missing some gains and losses
bt[, sum(is.na(gains))]
bt[, sum(is.na(losses))]

# make a long version summarized by rarefyID for plotting
btgainloss <- rbind(bt[, .(prop = mean(gains/S1), type = 'gain'), by = .(REALM, rarefyID)],
                    bt[, .(prop = mean(losses/S1), type = 'loss'), by = .(REALM, rarefyID)])

```

# Plot

```{r}
# plots
ggplot(btgainloss, aes(REALM, prop)) +
  geom_boxplot() +
  scale_y_log10() + 
  facet_wrap(~type)

```


# Stats
Nonparametric test of gains by realm.
```{r}
kruskal.test(prop ~ REALM, data = btgainloss[type == 'gain' & is.finite(prop), .(prop, REALM = as.factor(REALM))])

```

Nonparametric test of losses by realm.
```{r}
kruskal.test(prop ~ REALM, data = btgainloss[type == 'loss' & is.finite(prop), .(prop, REALM = as.factor(REALM))])

```
