---
title: "Initial dissimilarity and trend"
output: 
    github_document: default
---

```{r setup, include=FALSE}
library(data.table) # for handling large datasets
library(ggplot2) # for some plotting
library(glmmTMB) # for beta regression
library(here) # for navigating directories in the repo
if(Sys.info()['nodename'] == 'annotate.sebs.rutgers.edu'){
  library('mgcv', lib.loc = '/usr/lib64/R/library') # when running on Annotate. Need to load 1.8-26, not 1.8-33, for geom_smooth() in ggplot
} else {
  library('mgcv')
}
source(here('code', 'util.R')) # simple utility functions

# tell RStudio to use project root directory as the root for this notebook. Needed since we are storing code in a separate directory.
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) 

```

# Load data and set up
```{r}
# biotime community dissimilarity data
bt <- fread('output/turnover_w_covariates.csv.gz') # the timeseries that pass QA/QC. from assemble_turnover_covariates.Rmd
bt[, minduration := min(duration), by = rarefyID]
nrow(bt)

# turnover rate (slope of dissimilarity vs. time)
trends <- fread('output/slope.csv.gz') # linear slopes. from calc_turnover.R

# make frame of initial dissimilarities and turnover rates
initdiss <- bt[duration == minduration, .(Jtu.init = mean(Jtu.sc)), by = .(REALM, rarefyID)] # initial dissimilarities
nrow(initdiss)

# add slope to initdiss
initdiss <- merge(initdiss, trends[measure == 'Jtu' & duration_group == 'All'], by = 'rarefyID')
nrow(initdiss)

# add initdiss back to bt
bt <- merge(bt, initdiss[, .(rarefyID, Jtu.init)])
nrow(bt)

```

# Plot
Turnover rate depends somewhat on number of temporal samples.
```{r}
initdiss[, log10nsamps := log10(nsamps)]
initdiss[, nsamps_class := NA_character_]
initdiss[nsamps == 3, nsamps_class := '3'] # turnover rate isn't meaningful for <3 samples, since need at least 2 dissimilarity values
initdiss[nsamps == 4, nsamps_class := '4']
initdiss[nsamps == 5, nsamps_class := '5']
initdiss[nsamps > 5, nsamps_class := '>5']
initdiss[, nsamps_class := factor(nsamps_class, levels = c('3', '4', '5', '>5'))]


ggplot(initdiss[!is.na(nsamps_class)], aes(Jtu.init, disstrend, color = year2 - year1)) +
    geom_point() +
    geom_smooth() +
  facet_wrap(~nsamps_class, scales = "free_y") +
  scale_color_gradient(trans = 'log10')
  
```

Turnover rate depends on duration of the time series.
```{r}
initdiss[, duration_class := NA_character_]
initdiss[(year2 - year1) == 3, duration_class := '3']
initdiss[(year2 - year1) >= 4 & (year2 - year1) < 6, duration_class := '4-5']
initdiss[(year2 - year1) >=6 & (year2 - year1) < 11, duration_class := '6-10']
initdiss[(year2 - year1) >= 11 & (year2 - year1) < 20, duration_class := '11-20']
initdiss[(year2 - year1) >= 21 & (year2 - year1) < 50, duration_class := '21-50']
initdiss[(year2 - year1) >= 51, duration_class := '>51']
initdiss[, duration_class := factor(duration_class, levels = c('3', '4-5', '6-10', '11-20', '21-50', '>51'))]


ggplot(initdiss[!is.na(duration_class) & nsamps > 2], aes(Jtu.init, disstrend, color = nsamps)) + # need at least 3 samples to get 2 dissimilarities to plot a meaningful slope
    geom_point(alpha = 0.5) +
    geom_smooth() +
  facet_wrap(~duration_class, scales = "free_y") +
  scale_color_gradient(trans = 'log10')
  
```


# Statistical test
Need to first fit a one-stage ME model with beta errors with turnover_vs_init_GLMM_fit.R.
```{r}
if(!exists('modInitAllJtu')) modInitAllJtu <- readRDS(here('temp', 'modInitAllJtu.rds')) # Fit by code/turnover_vs_init_GLMM_fit.R
summary(modInitAllJtu)
```


# Predictions from the model
```{r}
newdat <- data.table(expand.grid(duration = 1:10, REALM = c('Marine', 'Terrestrial', 'Freshwater'), Jtu.init = seq(0,1, length.out = 5)))
newdat$STUDY_ID <- 1
newdat$rarefyID <- 1

#preds <- predict(modInitAllJtu, newdata = newdat, se.fit = TRUE, re.form = NA, allow.new.levels=TRUE, type = 'response')
#newdat$Jtu.sc <- preds$fit
#newdat$Jtu.sc.se <- preds$se.fit

# Calculate predicted probabilities manually (since predict() is very slow)
m <- model.matrix(~ duration + Jtu.init:duration, newdat)[,]
newdat[, Jtu.sc.linear := fixef(modInitAllJtu)$cond %*% t(m)] # predicted values on linear scale
newdat[, Jtu.sc := plogis(Jtu.sc.linear)] # back to response scale

# convert dissimilarity values into turnover rate (slope)
newdat.slopes <- newdat[, .(disstrend = coef(lm(Jtu.sc ~ duration))[2]), by = Jtu.init]
```

# Plot predictions
The dissimilarity values
```{r}
ggplot(newdat, aes(duration, Jtu.sc, color = Jtu.init, group = Jtu.init)) +
  geom_line()

```


The turnover rates
```{r}
ggplot(newdat.slopes, aes(Jtu.init, disstrend)) +
  geom_point()

```


